modify pre-commit to basically check that `black` doesn't need to be run on `_notebooks`, and stop the commit if it does... (can improve this workflow in future if needed...)

diff --git a/_git_hooks/pre-commit b/_git_hooks/pre-commit
--- a/_git_hooks/pre-commit
+++ b/_git_hooks/pre-commit
@@ -5,4 +5,8 @@ if [ "$NO_GIT_HOOKS" = true ]; then
     echo NO_GIT_HOOKS="$NO_GIT_HOOKS" so aborting hook.
     exit 0
 fi
-black _notebooks
+
+black _notebooks --check
+[ $? -ne 0 ] && echo "Aborting commit: run black before committing." && exit 1
+
+echo "Pre-commit completed successfully."
